from sqlalchemy import Column, Integer, String, ForeignKey, DateTime, Text
from sqlalchemy.orm import relationship
from pgvector.sqlalchemy import Vector
from datetime import datetime, UTC
from .database import Base


class Document(Base):
    """
    SQLAlchemy model representing an uploaded document.

    This table stores high-level metadata about the file. It serves as the parent
    entity for text segments (chunks) generated during the ingestion process.

    Attributes:
        id (int): Unique identifier for the document.
        filename (str): The original name of the uploaded file.
        created_at (datetime): Timestamp of when the document was processed (UTC).
        chunks (list[DocumentChunk]): One-to-many relationship linking to the
            document's individual text segments.
    """

    __tablename__ = "documents"

    id = Column(Integer, primary_key=True, index=True)
    filename = Column(String)
    created_at = Column(DateTime, default=datetime.now(tz=UTC))

    # One-to-many: Document - DocumentChunk
    chunks = relationship(argument="DocumentChunk", back_populates="document")


class DocumentChunk(Base):
    """
    SQLAlchemy model representing a specific segment of a document.

    This table stores the actual text content and its corresponding semantic
    embedding. It is designed for efficient vector similarity searches.

    Attributes:
        id (int): Unique identifier for the chunk.
        document_id (int): Foreign key referencing the parent document.
        content (str): The raw text fragment (typically 500 characters).
        embedding (Vector): A 384-dimensional vector generated by the
            all-MiniLM-L6-v2 model.
        document (Document): Many-to-one relationship linking back to the owner document.
    """

    __tablename__ = "document_chunks"

    id = Column(Integer, primary_key=True, index=True)
    document_id = Column(Integer, ForeignKey(column="documents.id"))
    content = Column(Text)

    # 384 is the dimension of all-MiniLM-L6-v2.
    embedding = Column(Vector(dim=384))
    
    # Many-to-one: DocumentChunk - Document
    document = relationship(argument="Document", back_populates="chunks")
